# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 720110434c3006631540a16090b0fb4eb6b807a7bc580912fa2bfd6633588eacf7d2d52ae0c82ecc23dcc48938b3fd9313033e10672da7412e09d2a385ec423b

test:
  secret_key_base: 7dbd13e2c0cd45a547ede7b2914885814b6c07315bc58885ed2c93fccaadfc0d820ab0bdc5ddbe374392a6df495cf0ed5e9e6d70fd92e50078e25030ac36cb4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
